version: "3.7"
services:
  urlwatch:
   container_name: urlwatch
   image: ghcr.io/firebird76/urlwatch:latest
   build: .
   volumes:
       - ./urlwatch-log:/var/log/
       - ./urlwatch-root:/root/


