version: "3.7"
services:
  urlwatch:
    image: ghcr.io/firebird76/urlwatch:latest
    build: .
    volumes:
       - /volume2/docker/urlwatch/log:/var/log/
       - /volume2/docker/urlwatch/root:/root/


